package com.youzhi.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrder<M extends BaseOrder<M>> extends Model<M> implements IBean {

	public void setOId(java.lang.Integer oId) {
		set("o_id", oId);
	}
	
	public java.lang.Integer getOId() {
		return getInt("o_id");
	}

	public void setOGoodsId(java.lang.String oGoodsId) {
		set("o_goods_id", oGoodsId);
	}
	
	public java.lang.String getOGoodsId() {
		return getStr("o_goods_id");
	}

	public void setOGoodsName(java.lang.String oGoodsName) {
		set("o_goods_name", oGoodsName);
	}
	
	public java.lang.String getOGoodsName() {
		return getStr("o_goods_name");
	}

	public void setOGoodsMoney(java.lang.Double oGoodsMoney) {
		set("o_goods_money", oGoodsMoney);
	}
	
	public java.lang.Double getOGoodsMoney() {
		return getDouble("o_goods_money");
	}

	public void setOGoodsNumber(java.lang.Integer oGoodsNumber) {
		set("o_goods_number", oGoodsNumber);
	}
	
	public java.lang.Integer getOGoodsNumber() {
		return getInt("o_goods_number");
	}

	public void setOStudentId(java.lang.Integer oStudentId) {
		set("o_student_id", oStudentId);
	}
	
	public java.lang.Integer getOStudentId() {
		return getInt("o_student_id");
	}

}
