package com.youzhi.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseGoods<M extends BaseGoods<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setImage(java.lang.String image) {
		set("image", image);
	}
	
	public java.lang.String getImage() {
		return getStr("image");
	}

	public void setGoodsName(java.lang.String goodsName) {
		set("goodsName", goodsName);
	}
	
	public java.lang.String getGoodsName() {
		return getStr("goodsName");
	}

	public void setPrice(java.lang.Double price) {
		set("price", price);
	}
	
	public java.lang.Double getPrice() {
		return getDouble("price");
	}

	public void setNumber(java.lang.Integer number) {
		set("number", number);
	}
	
	public java.lang.Integer getNumber() {
		return getInt("number");
	}

}
