package com.youzhi.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCart<M extends BaseCart<M>> extends Model<M> implements IBean {

	public void setCId(java.lang.Integer cId) {
		set("c_id", cId);
	}
	
	public java.lang.Integer getCId() {
		return getInt("c_id");
	}

	public void setCGoodsId(java.lang.Integer cGoodsId) {
		set("c_goods_id", cGoodsId);
	}
	
	public java.lang.Integer getCGoodsId() {
		return getInt("c_goods_id");
	}

	public void setCGoodsName(java.lang.String cGoodsName) {
		set("c_goods_name", cGoodsName);
	}
	
	public java.lang.String getCGoodsName() {
		return getStr("c_goods_name");
	}

	public void setCStudentId(java.lang.Integer cStudentId) {
		set("c_student_id", cStudentId);
	}
	
	public java.lang.Integer getCStudentId() {
		return getInt("c_student_id");
	}

}
